services:
  - type: web
    name: pintaai
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: IMAGE_PROVIDER
        value: qwen
      - key: IMAGE_MODEL
        value: qwen-image-edit-plus
      - key: QWEN_MODEL
        value: qwen-image-edit-plus
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: DASHSCOPE_BASE_URL
        sync: false
